// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "SudoMode.ENTER_PASSWORD": "Enter your password",
    "SudoMode.HELP_TEXT": "What is this?",
    "SudoMode.VERIFY": "Verify",
    "SudoMode.VERIFY_ITS_YOU": "Verify it's you first.",
    "SudoMode.VERIFY_TO_CONTINUE": "Verify to continue"
});
}