// This file was generated by silverstripe/tx-translator from client/lang/src/eo.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('eo', {
    "SudoMode.ENTER_PASSWORD": "Enigu vian pasvorton",
    "SudoMode.HELP_TEXT": "Kio estas tio?",
    "SudoMode.VERIFY": "Aŭtentigi",
    "SudoMode.VERIFY_ITS_YOU": "Unue aŭtentigi vin.",
    "SudoMode.VERIFY_TO_CONTINUE": "Aŭtentigi por daŭrigi"
});
}