// This file was generated by silverstripe/tx-translator from client/lang/src/nl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "SudoMode.ENTER_PASSWORD": "Voer wachtwoord in",
    "SudoMode.HELP_TEXT": "Wat is dit?",
    "SudoMode.VERIFY": "Bevestig",
    "SudoMode.VERIFY_ITS_YOU": "Verifieer dat dit je eerste is.",
    "SudoMode.VERIFY_TO_CONTINUE": "Bevestig om door te gaan"
});
}