// This file was generated by silverstripe/tx-translator from client/lang/src/sk.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sk', {
    "SudoMode.ENTER_PASSWORD": "Zadajte svoje heslo",
    "SudoMode.HELP_TEXT": "Čo je toto?",
    "SudoMode.VERIFY": "Overiť",
    "SudoMode.VERIFY_ITS_YOU": "Najprv overte, že ste to vy.",
    "SudoMode.VERIFY_TO_CONTINUE": "Ak chcete pokračovať, overte"
});
}