// This file was generated by silverstripe/tx-translator from client/lang/src/sl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sl', {
    "SudoMode.ENTER_PASSWORD": "Vnesite vaše geslo",
    "SudoMode.HELP_TEXT": "Kaj je to?",
    "SudoMode.VERIFY": "Preveri",
    "SudoMode.VERIFY_ITS_YOU": "Najprej potrdite, da ste to res vi.",
    "SudoMode.VERIFY_TO_CONTINUE": "Za nadaljevanje potrdite"
});
}