// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "SudoMode.ENTER_PASSWORD": "Ange ditt lösenord",
    "SudoMode.HELP_TEXT": "Vad är detta?",
    "SudoMode.VERIFY": "Verifiera",
    "SudoMode.VERIFY_ITS_YOU": "Verify it's you first.",
    "SudoMode.VERIFY_TO_CONTINUE": "Verifiera för att fortsätta"
});
}